Final/Final/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^', include('TartanList.urls')),
)

Final/TartanList/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # home & profile 
    url(r'^$', 'TartanList.views.home', name='home'),
    url(r'^home$', 'TartanList.views.home', name='home'),
    url(r'^cover$', 'TartanList.views.cover', name='cover'),
    url(r'^profile$', 'TartanList.views.profile', name='profile'),
    url(r'^search', 'TartanList.views.search', name='search'),
    
    #login and registration 
    url(r'^login$', 'django.contrib.auth.views.login', {'template_name':'login.html'}, name = 'login'),
    url(r'^logout$', 'django.contrib.auth.views.logout_then_login', name = 'logout'),
    url(r'^register$', 'TartanList.views.register', name='register'),
    url(r'^confirm-registration/(?P<username>[a-zA-Z0-9_@\+\-]+)/(?P<token>[a-z0-9\-]+)$', 'TartanList.views.confirm_registration', name='confirm'),
    url(r'^reset$', 'TartanList.views.resetPassword', name='reset'),
    url(r'^confirm-email/(?P<username>[a-zA-Z0-9_@\+\-]+)/(?P<token>[a-z0-9\-]+)$', 'TartanList.views.confirm_email', name='confirm_email'),
    url(r'^enter-new-password$', 'TartanList.views.enter_new_password', name='enter-new-password'),
    
    #items url
    url(r'^item-add$', 'TartanList.views.item_add', name='item-add'),
    url(r'^item-add-new$', 'TartanList.views.item_add_new', name='item-add-new'),
    url(r'^item-photos/(?P<id>\d+)$', 'TartanList.views.item_photo', name='item-photo'),
    url(r'^item-sold/(?P<id>\d+)$', 'TartanList.views.item_sold', name='item-sold'),
    url(r'^item-delete/(?P<id>\d+)$', 'TartanList.views.item_delete', name='item-delete'),
    url(r'^item-detail/(?P<id>\d+)$', 'TartanList.views.item_detail', name='item-detail'),
    url(r'^item-edit/(?P<id>\d+)$', 'TartanList.views.item_edit', name='item-edit'),
    url(r'^item-contact/(?P<id>\d+)$', 'TartanList.views.item_contact', name='item-contact'),
   
    #edit url
    url(r'^edit$', 'TartanList.views.edit', name='edit'),
    url(r'^edit_name$', 'TartanList.views.edit_name', name='edit_name'),
    url(r'^edit_password$', 'TartanList.views.edit_password', name='edit_password'),
    url(r'^search$', 'TartanList.views.search', name='search'),
    
    #sort & filter
    url(r'^sort-filter$', 'TartanList.views.sort_filter', name='sort-filter')
)

Final/TartanList/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    
    CATEGORIES = (
        ('Appliances', 'Appliances'),
        ('Automotive', 'Automotive'),
        ('Books', 'Books'),
        ('Phones', 'Phones'),
        ('Clothing', 'Clothing'),
        ('Computers', 'Computers'),
        ('Electronics', 'Electronics'),
        ('Home', 'Home'),
        ('Rental', 'Rental'),
        ('Travel', 'Travel'),
        ('Office', 'Office'),
        ('Outdoors', 'Outdoors'),
        ('Other', 'Other'),
    )
    title = models.CharField(max_length=200)
    description  = models.CharField(max_length=5000)
    address = models.CharField(max_length=500, blank=True, default=None)
    itemURL = models.CharField(max_length=200, null=True, blank=True)
    category = models.CharField(max_length=100, choices=CATEGORIES, default='Other')
    sellBy = models.DateField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    user = models.ForeignKey(User)
    picture = models.ImageField(upload_to="item_photos", blank=True)
    latitude = models.CharField(max_length=200)
    longitude = models.CharField(max_length=200)
    def __unicode__(self):
        return unicode(self.title) or u''

class SoldItem(models.Model):
    item = models.ForeignKey(Item)
    user = models.ForeignKey(User)
    def __unicode__(self):
        return unicode(self.item) or u''
        
class ExpressedInterestItem(models.Model):
    item = models.ForeignKey(Item)
    user = models.ForeignKey(User)
    def __unicode__(self):
        return unicode(self.item) or u''

Final/TartanList/views.py
from django.shortcuts import render_to_response
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.db import transaction

from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate

from TartanList.models import *
from TartanList.forms import *
from mimetypes import guess_type

from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.http import HttpResponse, Http404
from django.core import serializers

from django.db.models import Max
from django.db.models import Count
from decimal import Decimal

import simplejson, urllib
import requests
import json

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# home and profile
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

@login_required
def home(request):
    context = {}
    sold = SoldItem.objects.all().values('item_id')
    context['items'] = Item.objects.all().exclude(id__in=sold).exclude(user=request.user)
    context['SearchForm'] = SearchForm()
    context['FilterForm'] = FilterForm()
    context['PriceForm'] = PriceForm()
    context['SortForm'] = SortForm()
    return render(request, 'home.html', context)

def cover(request):
    return render_to_response('cover.html')

@login_required
def profile(request):
    context = {}
    context['SearchForm'] = SearchForm()
    sold = SoldItem.objects.filter(user=request.user).values('item_id')
    expressed = ExpressedInterestItem.objects.filter(user=request.user).values('item_id')
    context['expressed'] = Item.objects.filter(id__in=expressed)
    context['sold'] = Item.objects.filter(id__in=sold)
    context['items'] = Item.objects.filter(user=request.user).exclude(id__in=sold)

    return render(request, 'profile.html', context)

@login_required
def search(request):
    context = {}

    if request.method == 'POST':
        return redirect('home')

    context['SearchForm'] = SearchForm(request.GET)

    if not context['SearchForm'].is_valid():
        return render(request,'search.html',context)

    sold = SoldItem.objects.all().values('item_id')
    context['items'] = Item.objects.filter(title__icontains=context['SearchForm'].cleaned_data['search']).exclude(id__in=sold).exclude(user=request.user)
    context['search_value'] = str(context['SearchForm'].cleaned_data['search'])

    for cat in context['items'].values('category').annotate(total=Count('category')):
        context[str(cat['category'])] = cat['total']

    return render(request, 'search.html', context)

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# login and registration
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

def register(request):
    context = {}

    if request.method == 'GET':
        context['RegistrationForm'] = RegistrationForm()
        return render(request, 'register.html', context)

    form = RegistrationForm(request.POST)
    context['RegistrationForm'] = form

    # Validates the form.
    if not form.is_valid():
        return render(request, 'register.html', context)

    new_user = User.objects.create_user(username = form.cleaned_data['username'], 
                                        password = form.cleaned_data['password1'],
                                        email = form.cleaned_data['email'],
                                        first_name = form.cleaned_data['first_name'],
                                        last_name = form.cleaned_data['last_name'])

    new_user.is_active = False
    new_user.save()

    token = default_token_generator.make_token(new_user)

    email_body = """
    Welcome to the Tartan's List """ + new_user.first_name + """! 

        Username: """ + new_user.username + """

    Please click the link below to verify your email address and complete the registration of your account:
    
        http://%s%s
    """ % (request.get_host(), 
    reverse('confirm', args=(new_user.username, token)))

    send_simple_message(request, new_user, email_body)

    context['email'] = form.cleaned_data['email']
    return render(request, 'needs-confirmation.html', context)
    

def confirm_registration(request, username, token):
    context = {}
    user = get_object_or_404(User, username=username)

    if not default_token_generator.check_token(user, token):
        raise Http404

    user.is_active = True
    user.save()
    context['welcome'] = "Thank you for confirming your email address."
    return render(request, 'login.html', context)
     
    
def resetPassword(request):
    context = {}

    if request.method == 'GET':
        context['ResetPasswordForm'] = ResetPasswordForm()
        return render(request, 'reset-password.html', context)

    form = ResetPasswordForm(request.POST)
    context['ResetPasswordForm'] = form
    
    if not form.is_valid():
        return render(request, 'reset_password.html', context)
    
    email = form.cleaned_data['email']
    current_user = User.objects.filter(email__exact = email)[0]

    token = default_token_generator.make_token(current_user)

    email_body = """  
    Please click the link below to
    verify your email address and complete the password reset:

      http://%s%s
    """ % (request.get_host(), 
    reverse('confirm_email', args=(current_user.username, token)))

    send_simple_message(request, current_user, email_body)

    context['email'] = form.cleaned_data['email']
    return render(request, 'needs-confirmation.html', context)
    
def confirm_email(request, username, token):
    context = {}
    user = get_object_or_404(User, username=username)

    # Send 404 error if token is invalid
    if not default_token_generator.check_token(user, token):
        raise Http404

    context['welcome'] = "Your email has been confirmed, please enter a new password."
    context['EnterNewPasswordForm'] = EnterNewPasswordForm()
    context['email'] = user.email
    return render(request, 'enter-new-password.html', context) 

def enter_new_password(request):
    context = {}

    if request.method == 'GET':
        return redirect('login')

    form = EnterNewPasswordForm(request.POST)
    context['EnterNewPasswordForm'] = form

    if not form.is_valid():
        return render(request, 'enter-new-password.html', context)
        
    email = request.POST['email']
    u = User.objects.filter(email__exact = email)[0]
    new_password = form.cleaned_data['password3']
    u.set_password(new_password)
    u.save() 

    context['welcome'] = "Your password has been updated, please login."
    return render(request, 'login.html', context)    

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# items
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 

@login_required    
def item_add(request):
    context = {}
    context['SearchForm'] = SearchForm()
    current_user = request.user
    context['ItemForm'] = ItemForm()
    context['expressed'] = ''
    sold = current_user.solditem_set.all()
    context['sold'] = Item.objects.filter(id__in=sold)
    context['items'] = Item.objects.filter(user=request.user).exclude(id__in=sold.values('item_id'))
    return render(request, 'item-add.html', context)

@login_required
@transaction.atomic
def item_add_new(request):
    context = {}
    context['SearchForm'] = SearchForm()
    if request.method == 'GET':
        return redirect('item-add')

    new_item = Item(user=request.user)
    form = ItemForm(request.POST, request.FILES, instance=new_item)
    context['ItemForm'] = form

    if not form.is_valid():
        return render(request, 'item-add.html', context)
        
    address = str(form.cleaned_data['address'])
    if address:
        address_string = address.replace(" ","+")

        url = "https://maps.googleapis.com/maps/api/geocode/json?address="+address_string+"&key=##########"

        #cite the url from google web services website in the READ ME - Laura will do it
        result = simplejson.load(urllib.urlopen(url))
        l1 =  simplejson.dumps([s['geometry']['location']['lat'] for s in result['results']], indent=2)
        l2 =  simplejson.dumps([s['geometry']['location']['lng'] for s in result['results']], indent=2)

        lat = l1.translate(None, '[]').replace(' ','')
        lng = l2.translate(None, '[]').replace(' ','')

    if address:
        new_item = Item(user = request.user, latitude = lat.split(',')[0], longitude = lng.split(',')[0])
        form = ItemForm(request.POST, request.FILES, instance=new_item)
        if not form.is_valid():
            return render(request, 'item-add.html', context)

    form.save()
    return redirect('profile')

@login_required
@transaction.atomic
def item_photo(request, id):
    item = Item.objects.get(id__exact=id)
    entry = get_object_or_404(Item, id=id)

    if not entry.picture:
        raise Http404

    content_type = guess_type(entry.picture.name)
    return HttpResponse(entry.picture, content_type=content_type)

@login_required
def item_sold(request, id):
    item = Item.objects.get(id__exact=id)
    user = request.user
    
    sold = SoldItem.objects.filter(user=user, item=item)
    if not sold:
        new_soldItem = SoldItem(item=item,user=user)
        new_soldItem.save()

    return redirect('profile')
       
@login_required
def item_delete(request, id):
    context = {}
    try:
        item_to_delete = Item.objects.get(id=id, user=request.user)
        item_to_delete.delete()
    except ObjectDoesNotExist:
        context['errors'] = 'The item does not exist!'

    return redirect('edit')

@login_required

Final/TartanList/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
	  	<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
	  	<meta charset="UTF-8">
	    <title>{% block title %} Tartan's List {% endblock %}</title>
	
		{% block imports %}
		
		    <!-- jQuery -->
		    <script src="/../../static/jquery/jquery-1.11.1.js"></script>
		    <script src="/../../static/jquery/bootstrap-datepicker.js"></script>

			<!-- Bootstrap Tab Javascript for the website -->
			<script src="/../../static/bootstrap/js/bootstrap.js">
			    	$(function () {
			        	$('#myTab a:last').tab('show')
			      	});
		    </script>
	
			{% block javascript %}{% endblock %}
	
			<!-- Custom CSS file-->
		    <link rel="stylesheet" href="/../../static/style/custom.css">
		    <link rel="stylesheet" href="/../../static/style/datepicker.css">
            <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Raleway:200,300,400,500">  

		    <!-- Latest Bootstrap CSS -->
		    <link rel="stylesheet" href="/../../static/bootstrap/css/bootstrap.min.css">
		    
			<!-- Icon for the website -->	    
			<link rel="icon" type="image/png" href="/../../static/images/favicon.ico">
			
		{% endblock %} 
	</head>
	
	{% block bodytag %} <body> {% endblock %}
	{% block navtitle %}
		<nav id = "navbarcolor" class="navbar navbar-default" role="navigation">
			<div class="container-fluid">
				<div class="navbar-header">
					<a id ="tartanlist" class="navbar-brand" href="{% url 'home' %}">Tartan's List</a>
				</div>
		{% block nav %}{% endblock %}
			</div>
		</nav>
	{% endblock %}
	
	<div class="row-margin">
		<div class="row">
            {% block row_content %} {% endblock %}
			<div class="col-xs-4 col-md-2">{% block side %}{% endblock %}</div>
			<div class="col-xs-8 col-md-10">{% block content %}{% endblock %}</div>
		</div>
	<div>
	
  </body>
</html>

Final/TartanList/templates/cover.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Tartan's List</title>

    <!-- Bootstrap core CSS -->
    <link href="/../static/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/../static/style/customtest.css" rel="stylesheet">

  </head>

  <body style="background-image: url(/../static/Images/pitts.jpg);background-repeat: no-repeat;background-size: cover;" >

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Tartan's List</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="#">Sign Up</a></li>
                  <li><a href="#">Contact</a></li>
                </ul>
              </nav>
            </div>
          </div>


        </div>

      </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="/../static/bootstrap/js/bootstrap.min.js"></script>
  </body>
</html>

Final/TartanList/templates/edit-item.html
{% extends "profile.html" %}
{% block title %} Tartan's List | Edit Item {% endblock %}
	
{% block content %}
    <div class="well well-sm">
		<h4 class="title">Edit Item</h4>
	</div>
	
    <div class="well">
		{% if EditItemForm.errors %}
	        <div class="alert alert-danger alert-dismissible" role="alert">
	            <button type="button" class="close" data-dismiss="alert">
	            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	            <strong>Error!</strong>
	            <br />
	            <ul>
		            {% for error in EditItemForm.non_field_errors %}
		                <li>{{ error }}</li>
		            {% endfor %}
		        </ul>
	        </div>
	    {% endif %}

	    <form method="POST" enctype="multipart/form-data" action="{% url 'item-edit' item_id %}">
	        {% for field in EditItemForm.visible_fields %}
	            {{ field }} <br />
	        {% endfor %}
	        <br />
	        <button class="btn btn-lg btn-success btn-block" type="submit">Update</button>
	        {% csrf_token %}
	   </form> 
	</div>
	<script type="text/javascript">
		$(document).ready(function() {
		    $('#id_sellBy').datepicker();
		})
   	</script>
{% endblock %}

Final/TartanList/templates/edit.html
{% extends "nav_base.html" %}
{% block title %} Tartan's List | Edit {% endblock %}
	
{% block side %}
	<div class="panel panel-danger">
		<div id = "redhead" class="panel-heading">Name Change</div>
		<div id = "redbody" class="panel-body">
            {% if EditNameForm.errors %}
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <strong>Error!</strong>
                            {% for error in EditNameForm.non_field_errors %}
                                <p id="errortext" >{{ error }}</p>
                            {% endfor %}
                    </div>
            {% endif %}
			<form method="post" action="{% url 'edit_name' %}">
                {% for field in EditNameForm.visible_fields %}
                    {{ field }}
                {% endfor %}
                <br />
                <button class="btn btn-lg btn-danger btn-block" type="submit">Update</button>
                {% csrf_token %}
            </form>
		</div>
	</div>
	<div class="panel panel-danger">
		<div id = "redhead" class="panel-heading">Password Change</div>
		<div id = "redbody" class="panel-body">
            {% if EditPasswordForm.errors %}
                <div class="alert alert-danger alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert">
					<span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<strong>Error!</strong>
						{% for error in EditPasswordForm.non_field_errors %}
						    <p id="errortext" >{{  error }}</p>
						{% endfor %}
                </div>
            {% endif %}
            {% if errors %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <strong>Error!</strong>
                <br>
                <p id="errortext">{{ errors }}</p>
            </div>
            {% endif %}

            <form method="post" action="{% url 'edit_password' %}">
                {% for field in EditPasswordForm.visible_fields %}
                    {{ field }}
                {% endfor %}
                <br>
                <button class="btn btn-lg btn-danger btn-block" type="submit">Update</button>
                {% csrf_token %}
            </form> 
		</div>
	</div>
	
{% endblock %}
{% block content %}

	<div class="well well-sm">
		<div class="row">
			<div class="col-xs-4 col-md-4"><h4 class="title">{{ items.count }} Items found</h4></div>
			<div class="col-xs-6 col-md-6"></div>
			<div class="col-xs-2 col-md-2"></div>
		</div>
	</div>
	
	<div class="well">
		<div class="row">
			{% for item in items %}
				<!-- single item -->
				<div class="col-sm-6 col-md-3">
					<div class="thumbnail">
						{% if item.picture %}
                            <img src="{% url 'item-photo' item.id %}" alt="{{ item.title }}" class="thumbnail img-responsive">
                        {% else %}
                            <img src="/../../static/Images/default.png" > 
                        {% endif %}
						<div class="caption">
							<a href="{% url 'item-detail' item.id %}" class="thumb-item">{{ item.title }}</a>
							<br /><br />
							<a href="{% url 'item-edit' item.id %}">
								<button id="sideButton"  type="button" class="btn btn-danger btn-lg">Edit</button>
							</a>
							<br /><br />
							<a href="{% url 'item-delete' item.id %}">
								<button id="sideButton"  type="button" class="btn btn-danger btn-lg">Delete</button>
							</a>
						</div>
					</div>
				</div>
				<!-- end single item -->
			{% endfor %}
		</div>
	</div>
	
{% endblock %}

Final/TartanList/templates/enter-new-password.html
{% extends "base.html" %}
    
	{% block title %} TartanList | Forgot Password {% endblock %}
    
    {% block navtitle %}
		
		{% block nav %}{% endblock %}

	{% endblock %}
    

   	{% block bodytag %} <body id="bodywallpaper"> {% endblock %}

    {% block content %}
        <div class="sideForm">
            {% if welcome %}
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <strong>Thank you!</strong> 
                    <br />
                    {{ welcome }}
                </div>
            {% endif %}
            {% if EnterNewPasswordForm.non_field_errors %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <strong>Error!</strong>
                    <br />
                    {% for error in EnterNewPasswordForm.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            {% endif %}
            <form method="post" action="{% url 'enter-new-password' %}">
                {% for field in EnterNewPasswordForm.visible_fields %}
                    {{ field }}
                {% endfor %}
                <br />
                <input type="hidden" name="email" value="{{ email }}">
                <button class="btn btn-lg btn-danger btn-block" type="submit">Update</button>
                {% csrf_token %}
           </form> 
        </div>
    {% endblock %}


    <div class="container">
     
    </div> 

Final/TartanList/templates/item-add.html
{% extends "profile.html" %}
{% block title %} Tartan's List | Add {% endblock %}
	
{% block content %}
    <div class="well">
		<h4 class="title">Add New Item</h4>
	</div>
	
    <div class="well">
		{% if ItemForm.non_field_errors %}
	        <div class="alert alert-danger alert-dismissible" role="alert">
	            <button type="button" class="close" data-dismiss="alert">
	            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	            <strong>Error!</strong>
	            <br />
	            <ul>
		            {% for error in ItemForm.non_field_errors %}
		                <li>{{ error }}</li>
		            {% endfor %}
		        </ul>
	        </div>
	    {% endif %}
	    <form method="POST" enctype="multipart/form-data" action="{% url 'item-add-new' %}">
	        {% for field in ItemForm.visible_fields %}
	            {{ field }} <br />
	        {% endfor %}
	        <br />
	        <button class="btn btn-lg btn-success btn-block" type="submit">Add</button>
	        {% csrf_token %}
	   </form> 
	</div>
	<script type="text/javascript">
		$(document).ready(function() {
		    $('#id_sellBy').datepicker();
		})
   	</script>
{% endblock %}

Final/TartanList/templates/login.html
{% extends "base.html" %}
    
	{% block title %} TartanList | Login {% endblock %}
	
    {% block navtitle %}
		
		{% block nav %}{% endblock %}

	{% endblock %}
    

   	{% block bodytag %} <body id="bodywallpaper"> {% endblock %}
	
    {% block row_content %} <h1 id="welcometext" > Welcome to Tartan's List </h1>{% endblock %}
    
  	{% block content %}	
		<div class="sideForm">
			{% if welcome %}
				<div class="alert alert-warning alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert">
					<span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<strong>Welcome!</strong> 
					<br />
					{{ welcome }}
                </div>
			{% endif %}
			{% if form.errors %}
                <div class="alert alert-danger alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert">
					<span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<strong>Error!</strong>
					<br />
					{% for error in form.non_field_errors %}
					    {{ error }}
					{% endfor %}
                </div>
            {% endif %}
            <div id="formwell" class="well">
                <form class="form-group" method="POST" action="{% url 'django.contrib.auth.views.login' %}">
                    <input type="text" class="form-control" placeholder="Username" name="username" value="{{ username }}" required="">
                    <input type="password" class="form-control" placeholder="Password" name="password" value="{{ password }}" required="">
                    <br>
                    &nbsp<a id="forgotpassword" href="{% url 'reset' %}">Forgot password?</a> <br /><br />
                    <button id="sideButton" class="btn btn-lg btn-danger" type="submit">Sign In</button>
                    <hr>
                    {% csrf_token %}
                </form>
                <a href="{% url 'register' %}"><button id="sideButton" type="button" class="btn btn-danger btn-lg">Sign Up</button></a>
            </div>
		</div>
   
	{% endblock %}